CREATE TABLE NEWS(
 RANK REAL,
 HACKER_NEWS
);

INSERT INTO NEWS(RANK, HACKER_NEWS) VALUES
(7.5, 'ENGLISH HACKER ARRESTED!'),
(5.5, 'FATHER FORCES HIS CHILD INTO HACKING!'),
(8.5, 'RUSSIA KILLS US HACKER!'),
(9.5, 'MYSTRY HACKER STRIKES AGAIN!'),
(3.5, 'HACKERS FINDS A NEW JOB!');


SELECT * FROM NEWS
ORDER BY RANK DESC;

